---
deployment:
  tasks:
    # Remove conflicting untracked files before merge
    - /usr/local/cpanel/3rdparty/bin/git checkout -- . || true
    - /usr/local/cpanel/3rdparty/bin/git clean -fd || true
    - echo "Deployment complete"
