<?php
// Auto-generated by build - serves dist/index.html with correct paths
// PHP output bypasses LiteSpeed static file cache
header('Content-Type: text/html; charset=UTF-8');
header('Cache-Control: no-cache, no-store, must-revalidate');
$html = file_get_contents(__DIR__ . '/dist/index.html');
$html = str_replace('/kreasi/assets/', '/kreasi/dist/assets/', $html);
echo $html;
