import path from 'path';
import fs from 'fs';
import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';

// Plugin: after build, clean up dist/ and generate root index.html for cPanel
function cPanelDeploy(): import('vite').Plugin {
  return {
    name: 'cpanel-deploy',
    closeBundle() {
      const distDir = path.resolve(__dirname, 'dist');
      const rootDir = path.resolve(__dirname);

      // Read the built HTML (entry is dev.html, so output is dist/dev.html)
      const srcHtml = path.join(distDir, 'dev.html');
      if (!fs.existsSync(srcHtml)) {
        console.warn('⚠️ dist/dev.html not found');
        return;
      }

      let html = fs.readFileSync(srcHtml, 'utf-8');
      
      // Rename dist/dev.html -> dist/index.html
      fs.renameSync(srcHtml, path.join(distDir, 'index.html'));
      
      // Generate root index.html that loads from dist/assets/
      const rootHtml = html.replace(/\/kreasi\/assets\//g, '/kreasi/dist/assets/');
      fs.writeFileSync(path.join(rootDir, 'index.html'), rootHtml, 'utf-8');
      
      // Generate index.php as fallback (bypasses LiteSpeed cache)
      const phpContent = `<?php
// Auto-generated by build - serves dist/index.html with correct paths
// PHP output bypasses LiteSpeed static file cache
header('Content-Type: text/html; charset=UTF-8');
header('Cache-Control: no-cache, no-store, must-revalidate');
$html = file_get_contents(__DIR__ . '/dist/index.html');
$html = str_replace('/kreasi/assets/', '/kreasi/dist/assets/', $html);
echo $html;
`;
      fs.writeFileSync(path.join(rootDir, 'index.php'), phpContent, 'utf-8');
      
      console.log('\\n✅ Generated root index.html & index.php');
      console.log('✅ dist/index.html ready');
      console.log('🚀 Build ready for cPanel deployment!\\n');
    }
  };
}

export default defineConfig(({ mode }) => {
    const env = loadEnv(mode, '.', '');
    const isProduction = mode === 'production';
    return {
      base: '/kreasi/',
      server: {
        port: 3000,
        host: '0.0.0.0',
      },
      plugins: [
        react(),
        isProduction && cPanelDeploy(),
      ].filter(Boolean),
      define: {
        'process.env.API_KEY': JSON.stringify(''),
        'process.env.GEMINI_API_KEY': JSON.stringify('')
      },
      resolve: {
        alias: {
          '@': path.resolve(__dirname, '.'),
        }
      },
      build: {
        rollupOptions: {
          input: path.resolve(__dirname, 'dev.html'),
        }
      }
    };
});
